[package]
authors = ["Michael Lodder <redmike7@gmail.com>"]
categories = ["cryptography", "algorithms"]
description = "Verifiable Secret Sharing Schemes for splitting, combining and verifying secret shares"
documentation = "https://docs.rs/vsss-rs"
edition = "2021"
homepage = "https://github.com/mikelodder7/vsss-rs"
keywords = ["crypto", "sharing", "secret", "verifiable"]
license = "Apache-2.0 OR MIT"
name = "vsss-rs"
readme = "README.md"
repository = "https://github.com/mikelodder7/vsss-rs"
version = "3.0.0-rc.0"

[features]
default = ["curve25519", "std"]
alloc = ["rand_core/alloc", "rand/alloc", "serde/alloc"]
curve25519 = ["curve25519-dalek", "sha2-9", "serde", "data-encoding"]
std = ["rand_core/std", "rand/std", "serde/std"]

[dependencies]
curve25519-dalek = { version = "3", optional = true }
data-encoding = { version = "2.3", optional = true }
elliptic-curve = { version = "0.13", features = ["ecdh"] }
rand = { version = "0.8", default-features = false }
rand_chacha = { version = "0.3", default-features = false }
rand_core = "0.6"
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }
sha2-9 = { version = "0.9", default-features = false, optional = true, package = "sha2" }
subtle = { version = "2.4" }
thiserror-no-std = "2.0"
uint-zigzag = "0.2"
zeroize = { version = "1", features = ["zeroize_derive"] }

[dev-dependencies]
bls12_381_plus = "0.8"
ed25519-dalek = "1.0"
k256 = { version = "0.13", features = ["arithmetic", "bits"] }
p256 = { version = "0.13", features = ["arithmetic", "bits"] }
rand_xorshift = "0.3"
rstest = "0.17"
serde_json = "1.0"
serde_bare = "0.5"
sha2 = "0.10"
x25519-dalek = "1.1"
